### ISSUE TITLE
Minor io.EOF issue

### ISSUE THREAD

**Issue by scunningham** [icza/backscanner#5]
When dealing with some unusal reader implementations, I came across a case where a ReadAt(buf) is returning an io.EOF error even when the buffer 'buf' is completely filled.    It seems that this is allowed by the [specification](https://pkg.go.dev/io#ReaderAt):

```
If the n = len(p) bytes returned by ReadAt are at the end of the input source, ReadAt may return either err == EOF or err == nil.
```

If back scanner sees an error on ReadAt, it bails out and ignores the valid input:

from https://github.com/icza/backscanner/blob/bf6beb754c70/backscanner.go#L163

```
        _, s.err = s.r.ReadAt(s.buf2, int64(s.pos))
	if s.err == nil {
		s.buf, s.buf2 = append(s.buf2, s.buf...), s.buf
	}
```

One way to fix this would be to ignore io.EOF  in the case where the buffer was completely filled:

```
	// ReadAt attempts to read full buff!
	var n int
	n, s.err = s.r.ReadAt(s.buf2, int64(s.pos))

	switch {
	case s.err == nil:
	case s.err == io.EOF && n == size:
		// Possible to get an io.EOF of full buff reader
		// See https://pkg.go.dev/io#ReaderAt
		s.err = nil
	default:
		return
	}

	s.buf, s.buf2 = append(s.buf2, s.buf...), s.buf
```

**Comment by icza** [comment]
Thanks for the report, added a test case reproducing this and also fixed it.

**Comment by scunningham** [comment]
Thank you! 🙇
